= Windows SuperFetch database format

Analysis of AGDB

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

A Windows SuperFetch database file is used by Microsoft Windows as part of a
memory management to analyze memory usage patterns over time to optimize memory
content. This specification is based on earlier work on the format and was
enhanced by analyzing test data.

This document is intended as a working document for the Windows SuperFetch
database format specification. Which should allow existing Open Source forensic
tooling to be able to process this file type.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Windows SuperFetch database format
| Classification: | Public
| Keywords: | SuperFetch
|===

[preface]
== License

....
Copyright (C) 2014-2019, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | April 2014 | Initial version.
| 0.0.2 | J.B. Metz | May 2014 | Additional findings.
| 0.0.3 | J.B. Metz | June 2014 | Additional findings.
| 0.0.4 | J.B. Metz | December 2014 | Switched to asccidoc format.
| 0.0.5 | J.B. Metz | November 2016 | Moved compression information to libfwnt documentation.
| 0.0.6 | J.B. Metz | December 2019 | Changes to formatting.
|===

:numbered:
== Overview

A Windows SuperFetch database file is used by Microsoft Windows as part of a
memory management to analyze memory usage patterns over time to optimize memory
content.

From `[MSDN]` SuperFetch prioritizes the following kinds of pages to remain in
memory:

* Pages of applications that are used most frequently overall.
* Pages of applications that are commonly used when resuming:
** After extensive hibernation (for example, first thing in the morning).
** After shorter periods of sleep or hibernation (for example, after lunch).

SuperFetch is implemented in %SystemRoot%\System32\sysmain.dll as a Windows
service that runs inside a Service Host process
(%SystemRoot%\System32\svchost.exe).

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | FILETIME in UTC
| Character strings | ASCII strings are Single Byte Character (SBC) or Multi Byte Character (MBC) string stored with a codepage. Sometimes referred to as ANSI string representation. +
Though technically maybe incorrect, this document will use term (extended) ASCII string. +
Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

=== Test version

Files created by the following version of programs were used to test the
information within this document:

* Windows Vista (SP0)
* Windows 7 (SP0)
* Windows 8.1

=== SuperFetch files

The SuperFetch files can be found in:
....
C:\Windows\Prefetch\
....

The SuperFetch database filenames are structured as:
....
Ag*.db
....

Various known database filenames are:

[cols="1,5",options="header"]
|===
| Filename | Description
| AgAppLaunch.db | [yellow-background]*Unknown; Different format?*
| AgCx_SC#.db +
AgCx_SC#_xxxxxxxxxxxxxxxx.db | [yellow-background]*Unknown; scenario databases?* +
Can contain executable information +
Where # is a decimal digit and x a hexadecimal digit. +
 +
Seen: +
AgCx_SC1.db, AgCx_SC2.db, AgCx_SC4.db +
AgCx_SC3_xxxxxxxxxxxxxxxx.db +
| AgCx_SC#_%SID%.snp.db | [yellow-background]*Unknown* +
Where # is a decimal digit and %SID% is a Windows NT Security identifier.
| AgGlFaultHistory.db | [yellow-background]*Unknown; History of Page Faults?*
| AgGlFgAppHistory.db | [yellow-background]*Unknown; History of foreground applications?*
| AgGlGlobalHistory.db | [yellow-background]*Unknown*
| AgGlUAD_%SID%.db | [yellow-background]*Unknown; User Assist related?* +
Where %SID% is a Windows NT Security identifier.
| AgGlUAD_P_%SID%.db | [yellow-background]*Unknown; User Assist related?* +
Where %SID% is a Windows NT Security identifier. +
Can contain executable information
| AgRobust.db | Robust performance database +
Robust performance (or robustness) is a component of SuperFetch to watch for specific file I/O access that might harm system performance by populating the standby lists with unneeded data. +
 +
The source information contains process information including prefetch hashes.
| AgTwCont.db | [yellow-background]*Unknown; not seen*
| HIDBG-*-*-*.db | [yellow-background]*Unknown; not seen*
| LongTermHist.db | [yellow-background]*Unknown; not seen*
| NvGeneralUseCore.db | [yellow-background]*Unknown; not seen* +
[yellow-background]*Related to %SystemRoot%\System32\Nv ?*
| NvGeneralUseCore_Round*.db | [yellow-background]*Unknown; not seen* +
[yellow-background]*Related to %SystemRoot%\System32\Nv ?*
| NoPfnRefPages*.db | [yellow-background]*Unknown; not seen*
| NvcBoot.db | [yellow-background]*Unknown; not seen*
| NvcHiber.db | [yellow-background]*Unknown; not seen*
| Prefetch_%HASH%_*.db | [yellow-background]*Unknown; not seen* +
Where %HASH% is [yellow-background]*TODO*
| PfnDBCore*.db | [yellow-background]*Unknown; not seen*
| PfnDBKnown*.db | [yellow-background]*Unknown; not seen*
| PfnDBNoPFNEntry*.db | [yellow-background]*Unknown; not seen*
| PfnDBNoUDEntry*.db | [yellow-background]*Unknown; not seen*
| StorePages*.db | [yellow-background]*Unknown; not seen*
| WsCompPages*.db | [yellow-background]*Unknown; not seen*
| .core.db | [yellow-background]*Unknown; not seen*
| *.h.db | [yellow-background]*Unknown; not seen*
|===

The SuperFetch service is managed by the File Information FS MiniFilter
service. It appears that most of the SuperFetch database files are updated
(written) when the service is shut down. AgAppLaunch.db is also written when
the service starts.

These database files can be stored in multiple formats:

[cols="1,1",options="header"]
|===
| Characteristics | Description
| Compressed SuperFetch database - MAM file format | Used in Windows 8
| Compressed SuperFetch database - MEMO file format | Used in Windows Vista
| Compressed SuperFetch database - MEM0 file format | Used in Windows 7
| Uncompressed SuperFetch database file format | Used in Windows Vista, 7 and 8
|===

[yellow-background]*TODO*

The SuperFetch database [yellow-background]*trace* filenames are structured as:
....
Ag*.db.trx
....

== Compressed SuperFetch database - MEMO file format

A compressed SuperFetch database - MEMO file consist of the following
distinguishable elements:

* file header
* compressed blocks

The compression method is LZNT1

=== File header

The file header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MEMO" (0x4d, 0x45, 0x4d, 0x4f) | Signature
| 4 | 4 | | Total uncompressed data size
|===

=== Compressed block

The compressed block size is the chunk data size, which is part of the LZNT1
compressed data, + 2 bytes for the size of the chunk header itself.

The uncompressed block size is 4096 (0x1000) or the remaining uncompressed data
size for the last block.

For more information about LZNT1 see:
https://github.com/libyal/libfwnt/blob/master/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Compressed SuperFetch database - MEM0 file format

A compressed SuperFetch database - MEM0 file consist of the following
distinguishable elements:

* file header
* compressed blocks

The compression method is Microsoft XPRESS Huffman (or LZXPRESS). Note that
this is a different compression method as Microsoft XPRESS (LZ77+DIRECT2).

=== File header

The file header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MEM0" (0x4d, 0x45, 0x4d, 0x30) | Signature
| 4 | 4 | | Total uncompressed data size
|===

=== Compressed block

The compressed block is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Compressed data size
| 4 | ... | | LZXPRESS Huffman compressed data
|===

The uncompressed block size is 65536 (0x10000) or the remaining uncompressed
data size for the last block.

For more information about LZXPRESS Huffman see:
https://github.com/libyal/libfwnt/blob/master/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Compressed SuperFetch database - MAM file format

A compressed SuperFetch database - MAM file consist of the following
distinguishable elements:

* file header
* compressed stream

The compression method is Microsoft XPRESS Huffman (or LZXPRESS). Note that
this is a different compression method as Microsoft XPRESS (LZ77+DIRECT2).

=== File header

The file header is 12 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MAM\x84" (0x4d, 0x41, 0x4d, 0x84) | Signature
| 4 | 4 | | Total uncompressed data size
| 8 | 4 | | [yellow-background]*Unknown (checksum?)*
|===

=== Compressed stream

The compressed stream is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | LZXPRESS Huffman compressed data
|===

The compression stream differs from the compressed blocks as used in the MEM0
format. In the stream the compressed data can refer to uncompressed data stored in
previous compressed chunks.

For more information about LZXPRESS Huffman see:
https://github.com/libyal/libfwnt/blob/master/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Uncompressed SuperFetch database file format

An uncompressed SuperFetch database consist of the following distinguishable elements:

* file header
** database header
* volume information entries
** file information entries
* source information entries

=== Common data structures

==== [[ntfs_file_reference]]NTFS file reference

The NTFS file reference is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 6 | | MFT entry index
| 6 | 2 | | Sequence number
|===

=== File header

The file header is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | |  [yellow-background]*Unknown (signature or database type?)* +
[yellow-background]*0x00000005 or used by AgAppLaunch.db* +
[yellow-background]*0x0000000e or 0x0000000f used by others*
| 4 | 4 | | Total file size
| 8 | 4 | | File header size
| 12 | ... | | Database header
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== Database header

===== Common database header

The common database header is 60 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Database type +
See section: <<database_types_and_parameters,Database types and parameters>>
| 12 | 4 x 9 = 36 | | Database parameters
| 40 | 4 | | Number of volumes
| 44 | 4 | | Total number of files
| 48 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Does not appear to be the total number of sub entries type 1 or volumes information section size.)* +
 +
[yellow-background]*Part of the identifier value?*
| 52 | 4 | | Number of sources
| 56 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Does not appear to be the total number of sub entries type 2 or source information section size.*
|===

===== Database header 68 (64-bit)

AgCx_S#_%SID%.snp.db
....
00000000: 0c 00 00 00 48 00 00 00  40 00 00 00 58 00 00 00   ....H... @...X...
00000010: 18 00 00 00 10 00 00 00  10 00 00 00 10 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 ad 0e 00 00   ........ ........
00000030: 62 05 0f 00 83 00 00 00  38 5e 06 00 01 00 00 00   b....... 8^......
00000040: 8e 01 00 00                                        ....
....

The database header 68 is 68 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
|===

===== Database header 116 (32-bit)

The database header 116 is 116 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | 5 | [yellow-background]*Unknown* +
[yellow-background]*(hard coded to be 5?)*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown (Empty values?)*
|===

....
00000000: 0e 00 00 00 38 00 00 00  48 00 00 00 64 00 00 00   ....8... H...d...
00000010: 08 00 00 00 08 00 00 00  08 00 00 00 08 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  01 00 00 00 f9 01 00 00   ........ ........
00000030: 00 00 00 00 f2 00 00 00  d4 ee 00 00 05 00 00 00   ........ ........

00000040: c4 5c 7f 04 84 56 7f 04  b0 64 7f 04 fc cc c2 04   .\...V.. .d......
00000050: c7 00 00 00 2b 00 00 00  b8 79 c2 04 a0 91 c2 04   ....+... .y......
00000060: a0 5b c2 04 78 77 c2 04  e9 01 00 00 10 00 00 00   .[..xw.. ........
00000070: 00 00 00 00                                        ....
....

===== Database header 156 (64-bit)

The database header 156 is 156 bytes of size and consists of:

AgRobust.db (Windows 7 64-bit)
....
00000000: 0e 00 00 00 48 00 00 00  70 00 00 00 90 00 00 00   ....H... p.......
00000010: 10 00 00 00 10 00 00 00  10 00 00 00 10 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  13 00 00 00 4a 01 00 00   ........ ....J...
00000030: 00 00 00 00 f2 00 00 00  c2 e0 00 00 05 00 00 00   ........ ........
00000040: 00 00 00 00 38 24 63 0d  00 00 00 00 08 39 63 0d   ....8$c. .....9c.
00000050: 00 00 00 00 18 13 63 0d  00 00 00 00 88 66 63 0d   ......c. .....fc.
00000060: 00 00 00 00 c8 00 00 00  2a 00 00 00 90 b1 f0 08   ........ *.......
00000070: 00 00 00 00 90 b1 f0 08  00 00 00 00 40 3d ec 08   ........ ....@=..
00000080: 00 00 00 00 90 53 ec 08  00 00 00 00 00 00 00 00   .....S.. ........
00000090: 4a 01 00 00 00 00 00 00  00 00 00 00               J....... ....
....

===== Database header 228 (32-bit)

The database header 228 is 228 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | Number of date and time values
| 108 | 15 x 8 = 120 | | Date and time values +
Array of FILETIME values +
Unused entries are set to 0
|===

AgCx_SC1.db (Windows Vista 32-bit)
....
00000000: 0b 00 00 00 38 00 00 00  24 00 00 00 3c 00 00 00   ....8... $...<...
00000010: 10 00 00 00 10 00 00 00  10 00 00 00 10 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 41 03 00 00   ........ ....A...
00000030: 53 ec 00 00 3e 00 00 00  40 08 01 00 0c 00 00 00   S...>... @.......

00000040: 1c 00 00 00 01 00 00 00  01 00 00 00 1e 41 05 08   ........ .....A..
00000050: 01 01 00 00 03 00 00 00  b9 18 00 00 50 c3 00 00   ........ ....P...

00000060: 70 11 01 00 c8 d7 64 6f  04 00 00 00 20 ca a9 07   p.....do .... ...
00000070: 7f 84 c8 01 f0 d7 d0 d4  f4 cd c8 01 c0 e9 5d 4d   ........ ......]M
00000080: 61 1a c9 01 b0 8e dc 75  22 3e cb 01 00 00 00 00   a......u ">......
00000090: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000a0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000b0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000c0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000e0: 00 00 00 00                                        ....
....

===== Database header 232 (32-bit)

The database header 232 is 232 bytes of size and consists of:

AgGlUAD_P_%SID%.db (Vista)
....
00000000: 0b 00 00 00 38 00 00 00  24 00 00 00 3c 00 00 00   ....8... $...<...
00000010: 10 00 00 00 10 00 00 00  10 00 00 00 10 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 29 09 00 00   ........ ....)...
00000030: 67 61 01 00 29 00 00 00  c2 17 07 00 0c 00 00 00   ga..)... ........
00000040: 0f 00 00 00 03 00 00 00  01 00 00 00 3c 3c 0a 0a   ........ ....<<..
00000050: 02 02 00 00 1a 00 00 00  3e c6 00 00 80 38 01 00   ........ >....8..
00000060: 80 38 01 00 00 00 00 00  03 00 00 00 00 00 00 00   .8...... ........
00000070: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
...
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000e0: 00 00 00 00                                        ....
....

===== Database header 236 (64-bit)

The database header 236 is 236 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown (empty values)* +
[yellow-background]*Number of date and time values?*
| 116 | 15 x 8 = 120 | | Date and time values +
Array of FILETIME values +
Unused entries are set to 0
|===

AgCx_SC1.db (Windows 7 64-bit)
....
00000000: 0b 00 00 00 48 00 00 00  40 00 00 00 58 00 00 00   ....H... @...X...
00000010: 18 00 00 00 18 00 00 00  18 00 00 00 18 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  03 00 00 00 e2 08 00 00   ........ ........
00000030: c0 d4 01 00 2a 00 00 00  d4 93 03 00 0e 00 00 00   ....*... ........

00000040: ef 04 00 00 01 00 00 00  02 00 00 00 1e 41 05 08   ........ .....A..
00000050: 01 01 00 00 03 00 00 00  39 24 01 00 50 c3 00 00   ........ 9$..P...

00000060: 70 11 01 00 f0 27 3b ea  fe 07 00 00 b4 01 00 00   p....';. ........
00000070: 00 00 00 00 10 e5 90 a3  d2 50 cf 01 80 26 c5 8f   ........ .P...&..
00000080: ec 50 cf 01 f0 9c be ba  71 52 cf 01 20 f9 0d 34   .P...... qR.. ..4
00000090: 86 52 cf 01 10 9f 48 99  31 53 cf 01 40 ae 9d 3a   .R....H. 1S..@..:
000000a0: 38 53 cf 01 30 27 fc 9a  4c 53 cf 01 b0 e2 03 c6   8S..0'.. LS......
000000b0: 56 53 cf 01 a0 bb 5a f4  80 53 cf 01 30 3e 9d 6f   VS....Z. .S..0>.o
000000c0: f6 53 cf 01 b0 b3 3f 96  14 54 cf 01 90 a9 5e ab   .S....?. .T....^.
000000d0: 23 54 cf 01 00 fc 26 a1  2a 54 cf 01 d0 07 2a 35   #T....&. *T....*5
000000e0: 44 54 cf 01 40 82 af fc  93 54 cf 01               DT..@... .T..
....

AgCx_SC2.db (Windows 7 64-bit)
....
00000000: 0b 00 00 00 48 00 00 00  40 00 00 00 58 00 00 00   ....H... @...X...
00000010: 18 00 00 00 18 00 00 00  18 00 00 00 18 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 fb 06 00 00   ........ ........
00000030: 94 eb 01 00 2c 00 00 00  e4 17 03 00 0e 00 00 00   ....,... ........
00000040: ef 04 00 00 01 00 00 00  01 00 00 00 3c 3c 0a 0a   ........ ....<<..
00000050: 02 02 00 00 00 00 00 00  c0 71 04 00 50 c3 00 00   ........ .q..P...
00000060: 50 c3 00 00 00 00 00 00  00 00 00 00 98 00 00 00   P....... ........
00000070: 00 00 00 00 a0 e2 ed 7e  1d 4a cf 01 b0 07 41 93   .......~ .J....A.
00000080: 16 4b cf 01 90 c2 eb 81  8c 4b cf 01 f0 52 d2 e5   .K...... .K...R..
00000090: 73 4c cf 01 e0 1e 23 5c  b9 4c cf 01 d0 db 62 14   sL....#\ .L....b.
000000a0: 96 4d cf 01 f0 9f f7 ea  54 4e cf 01 f0 68 b4 d9   .M...... TN...h..
000000b0: da 4e cf 01 b0 16 37 20  21 4f cf 01 f0 c5 0c db   .N....7  !O......
000000c0: eb 4f cf 01 40 30 ea 2b  44 50 cf 01 b0 6f d2 e0   .O..@0.+ DP...o..
000000d0: 1e 51 cf 01 30 a1 84 87  b8 52 cf 01 70 b2 f4 4c   .Q..0... .R..p..L
000000e0: b3 53 cf 01 b0 6c d9 8b  76 54 cf 01               .S...l.. vT..
....

AgCx_SC4.db (Windows 7 64-bit)
....
00000000: 0b 00 00 00 48 00 00 00  40 00 00 00 58 00 00 00   ....H... @...X...
00000010: 18 00 00 00 18 00 00 00  18 00 00 00 18 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 ea 06 00 00   ........ ........
00000030: 50 c3 00 00 00 00 00 00  3e 66 03 00 0e 00 00 00   P....... >f......
00000040: c7 04 00 00 02 00 00 00  01 00 00 00 3c 3c 0a 0a   ........ ....<<..
00000050: 02 02 00 00 00 00 00 00  c0 71 04 00 50 c3 00 00   ........ .q..P...
00000060: 50 c3 00 00 00 00 00 00  00 00 00 00 bc 00 00 00   P....... ........
00000070: 00 00 00 00 e0 fc d6 1a  e4 9f ce 01 80 2e c1 08   ........ ........
00000080: 9a a4 ce 01 e0 56 b4 fe  63 a5 ce 01 80 22 58 bc   .....V.. c...."X.
00000090: 19 aa ce 01 30 56 5d ce  e1 aa ce 01 80 27 d4 af   ....0V]. .....'..
000000a0: 82 b3 ce 01 80 24 1e ad  3e b8 ce 01 70 d9 00 bf   .....$.. >...p...
000000b0: f9 cc ce 01 40 81 8b 54  e5 d0 ce 01 80 76 65 49   ....@..T .....veI
000000c0: 3c e4 ce 01 d0 38 69 b3  9d 0c cf 01 e0 a8 2e b7   <....8i. ........
000000d0: 5c 18 cf 01 a0 ba 65 75  f3 23 cf 01 d0 ef c0 a3   \.....eu .#......
000000e0: 40 29 cf 01 a0 66 a9 fb  b4 2d cf 01               @)...f.. .-..
....

AgGlUAD_P_%SID%.db (Windows 7 64-bit)
....
00000000: 0b 00 00 00 48 00 00 00  40 00 00 00 58 00 00 00   ....H... @...X...
00000010: 18 00 00 00 18 00 00 00  18 00 00 00 18 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00                            ........ ........

00000020:                          01 00 00 00 af 08 00 00   ........ ........
00000030: 00 71 02 00 1d 00 00 00  32 76 04 00 0e 00 00 00   .q...... 2v......

00000040: f7 04 00 00 03 00 00 00  01 00 00 00 3c 3c 0a 0a   ........ ....<<..
00000050: 02 02 00 00 1a 00 00 00  c0 71 04 00 80 38 01 00   ........ .q...8..
00000060: 80 38 01 00 00 00 00 00  00 00 00 00 bb 03 00 00   .8...... ........
00000070: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000080: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000090: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000a0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000b0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000c0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00  00 00 00 00               ........ ....
....

===== Database header 264 (32-bit and 64-bit)

The database header 264 is 264 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown (empty values)*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown*
| 116 | 4 | | [yellow-background]*Unknown*
| 120 | 4 | | [yellow-background]*Unknown*
| 124 | 4 | | [yellow-background]*Unknown*
| 128 | ... | | [yellow-background]*TODO*
| 224 | 8 | | [yellow-background]*Unknown (empty values)*
| 232 | 32 | | Database filename +
ASCII string with end-of-string character +
Unused bytes are set to 0
|===

AgGlFaultHistory.db (Windows Vista 32-bit)
....
00000040: ab 01 00 00 00 00 00 00  f7 9b b5 ff 00 00 00 00   ........ ........
00000050: 00 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: 00 08 00 00 00 10 00 00  f7 5f 00 00 f7 5f 00 00   ........ ._..._..
00000070: 00 10 00 00 f7 5f 00 00  ff ff ff ff 00 00 00 00   ....._.. ........

00000080: 14 0a 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 5e 00 00 00 00 00 00 00  1c 00 00 00 ba 5c 00 00   ^....... .....\..
000000a0: 18 23 00 00 00 00 00 00  7f 01 00 00 00 00 00 00   .#...... ........
000000b0: a2 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000c0: 62 12 00 00 2d 0b 00 00  35 07 00 00 a7 01 00 00   b...-... 5.......
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 a7 01 00 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00  41 67 47 6c 46 61 75 6c   ........ AgGlFaul
000000f0: 74 48 69 73 74 6f 72 79  2e 64 62 00 00 00 00 00   tHistory .db.....
00000100: 00 00 00 00 00 00 00 00                            ........
....

AgGlFaultHistory.db (Windows 7 64-bit)
....
00000040: 06 10 02 00 00 00 00 00  a6 8e a0 ff 00 00 00 00   ........ ........
00000050: 06 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: dc 01 00 00 00 10 00 00  75 ba 00 00 75 ba 00 00   ........ u...u...
00000070: 00 10 00 00 51 fc 00 00  ff ff ff ff 00 00 00 00   ....Q... ........

00000080: 14 0a 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 5e 00 00 00 00 00 00 00  f5 22 00 00 82 96 15 00   ^....... ."......
000000a0: bf 41 23 00 00 00 00 00  51 05 00 00 00 00 00 00   .A#..... Q.......
000000b0: 93 b7 02 00 6a 04 eb 02  41 69 50 00 00 00 00 00   ....j... AiP.....
000000c0: 88 2e 01 00 3a 73 00 00  4e bb 00 00 00 10 02 00   ....:s.. N.......
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 f1 0f 02 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00                            ........ AgGlFaul

000000e0:                          41 67 47 6c 46 61 75 6c   ........ AgGlFaul
000000f0: 74 48 69 73 74 6f 72 79  2e 64 62 00 00 00 00 00   tHistory .db.....
00000100: 00 00 00 00 00 00 00 00                            ........
....

AgGlFgAppHistory.db (Windows Vista 32-bit)
....
00000040: ab 01 00 00 00 00 00 00  f7 9b b5 ff 00 00 00 00   ........ ........
00000050: 00 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: 00 08 00 00 00 20 00 00  dc 7f 01 00 70 ff 05 00   ..... .. ....p...
00000070: 00 20 00 00 e0 fe 0b 00  ff ff ff ff 00 00 00 00   . ...... ........

00000080: 14 0a 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 40 00 00 00 00 00 00 00  1c 00 00 00 00 00 00 00   @....... ........
000000a0: 00 00 00 00 00 00 00 00  6a 0e 00 00 00 00 00 00   ........ j.......
000000b0: 35 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   5....... ........
000000c0: 32 6d 00 00 7d 00 00 00  00 00 00 00 a7 01 00 00   2m..}... ........
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 a7 01 00 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00  41 67 47 6c 46 67 41 70   ........ AgGlFgAp
000000f0: 70 48 69 73 74 6f 72 79  2e 64 62 00 00 00 00 00   pHistory .db.....
00000100: 00 00 00 00 00 00 00 00                            ........
....

AgGlFgAppHistory.db (Windows 7 64-bit)
....
00000040: 06 10 02 00 00 00 00 00  a6 8e a0 ff 00 00 00 00   ........ ........
00000050: 06 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: 85 06 00 00 fd 1e 00 00  29 a1 00 00 3c 8a 02 00   ........ )...<...
00000070: 00 20 00 00 3a 8a 1f 00  ff ff ff ff 00 00 00 00   . ..:... ........

00000080: 14 0a 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 40 00 00 00 00 00 00 00  f5 22 00 00 15 ce 01 00   @....... ."......
000000a0: 91 11 03 00 00 00 00 00  b7 92 00 00 00 00 00 00   ........ ........
000000b0: 73 a8 00 00 57 01 2c 02  eb 29 22 00 00 00 00 00   s...W.,. .)".....
000000c0: 31 ec aa 00 44 10 00 00  e0 00 00 00 00 10 02 00   1...D... ........
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 f1 0f 02 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00  41 67 47 6c 46 67 41 70   ........ AgGlFgAp
000000f0: 70 48 69 73 74 6f 72 79  2e 64 62 00 00 00 00 00   pHistory .db.....
00000100: 00 00 00 00 00 00 00 00                            ........
....

AgGlGlobalHistory.db (Windows Vista 32-bit)
....
00000000: 01 00 00 00 38 00 00 00  34 00 00 00 44 00 00 00   ....8... 4...D...
00000010: 10 00 00 00 14 00 00 00  08 00 00 00 08 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 3d 24 00 00   ........ ....=$..
00000030: d8 0d 03 00 00 00 00 00  ca 82 13 00 00 00 00 00   ........ ........
00000040: ab 01 00 00 00 00 00 00  f7 9b b5 ff 00 00 00 00   ........ ........
00000050: 00 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: 00 08 00 00 00 20 00 00  39 7a 02 00 e6 e8 09 00   ..... .. 9z......
00000070: 00 20 00 00 e0 fe 0b 00  ff ff ff ff 00 00 00 00   . ...... ........
00000080: 14 0a 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 40 00 00 00 00 00 00 00  1d 00 00 00 00 00 00 00   @....... ........
000000a0: ce ad 00 00 00 00 00 00  3d 0b 00 00 00 00 00 00   ........ =.......
000000b0: 00 00 00 00 00 00 01 00  00 00 00 00 00 00 00 00   ........ ........
000000c0: 41 ac 05 00 fa 12 00 00  c2 00 00 00 a7 01 00 00   A....... ........
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 a7 01 00 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00  41 67 47 6c 47 6c 6f 62   ........ AgGlGlob
000000f0: 61 6c 48 69 73 74 6f 72  79 2e 64 62 00 00 00 00   alHistor y.db....
00000100: 00 00 00 00 00 00 00 00                            ........
....

AgGlGlobalHistory.db (Windows 7 64-bit)
....
00000000: 01 00 00 00 48 00 00 00  58 00 00 00 60 00 00 00   ....H... X...`...
00000010: 18 00 00 00 20 00 00 00  10 00 00 00 10 00 00 00   .... ... ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 86 27 00 00   ........ .....'..
00000030: be cf 09 00 00 00 00 00  a2 6f 16 00 06 50 01 00   ........ .o...P..
00000040: 0f 10 02 00 00 00 00 00  af 8e a0 ff 00 00 00 00   ........ ........
00000050: 06 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: 00 08 00 00 00 20 00 00  02 e2 07 00 3a 8a 1f 00   ..... .. ....:...
00000070: 00 20 00 00 3a 8a 1f 00  ff ff ff ff 00 00 00 00   . ..:... ........
00000080: 14 0a 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 40 00 00 00 00 00 00 00  f6 22 00 00 da 0a 00 00   @....... ."......
000000a0: a3 a8 55 00 00 00 00 00  71 2f 02 00 00 00 00 00   ..U..... q/......
000000b0: 00 00 00 00 2b 00 4d 00  f3 42 02 00 00 00 00 00   ....+.M. .B......
000000c0: 61 6b b5 04 79 f1 00 00  5e 41 00 00 09 10 02 00   ak..y... ^A......
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 fa 0f 02 00   ........ ........
000000e0: 00 00 00 00 00 00 00 00  41 67 47 6c 47 6c 6f 62   ........ AgGlGlob
000000f0: 61 6c 48 69 73 74 6f 72  79 2e 64 62 00 00 00 00   alHistor y.db....
00000100: 00 00 00 00 00 00 00 00                            ........
....

AgGlUAD_%SID%.db (Vista)
....
00000000: 01 00 00 00 38 00 00 00  34 00 00 00 44 00 00 00   ....8... 4...D...
00000010: 10 00 00 00 14 00 00 00  08 00 00 00 08 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  02 00 00 00 29 09 00 00   ........ ....)...
00000030: 1e 5f 00 00 00 00 00 00  c2 17 07 00 00 00 00 00   ._...... ........
00000040: 05 00 00 00 00 00 00 00  73 7a cb ff 00 00 00 00   ........ sz......
00000050: 00 00 00 00 00 00 00 00  00 00 00 00 14 00 00 00   ........ ........
00000060: 00 10 00 00 00 10 00 00  ee bf 00 00 dc 7f 01 00   ........ ........
00000070: 00 10 00 00 dc 7f 01 00  d5 7a 00 00 00 00 00 00   ........ .z......
00000080: 00 00 01 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000090: 54 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   T....... ........
000000a0: 00 00 00 00 00 00 00 00  47 00 00 00 00 00 00 00   ........ G.......
000000b0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
000000c0: 1f 56 02 00 26 52 00 00  00 00 00 00 00 00 00 00   .V..&R.. ........
000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
...
000000f0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000100: 00 00 00 00 00 00 00 00                            ........
....

==== [[database_types_and_parameters]]Database types and parameters

`[REWOLF11]` states that the database type is an index of a table that is
located in sysmain.dll and that the 9x 32-bit values that follow the database
type are parameters (named database parameters in this document).

These database parameters seem to specify the sizes of the structures used in
the sections that follow the file header. The values of the database parameters
seem to be dependent on the architecture of sysmain.dll.

===== 32-bit databases

[cols="3,1,1,3",options="header"]
|===
| Filename | Database +
header size | Database type | Database parameters
| AgGlFaultHistory.db | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlFgAppHistory.db | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlGlobalHistory.db | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlUAD_%SID%.db | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| | | |
| AgCx_SC#.db +
AgCx_SC#_xxxxxxxxxxxxxxxx.db | 228 | 11 | 56, 36, 60, 16, 16, 16, 16, 0, 0
| AgGlUAD_P_%SID%.db | 232 | 11 | 56, 36, 60, 16, 16, 16, 16, 0, 0
| AgCx_S#_%SID%.snp.db | | |
| | | |
| AgRobust.db | 116 | 14 | 56, 72, 100, 8, 8, 8, 8, 0, 0
|===

===== 64-bit databases

[cols="3,1,1,3",options="header"]
|===
| Filename | Database +
header size | Database type | Database parameters
| AgGlFaultHistory.db | 264 | 1 | 72, 88, 96, 24, 32, 16, 16, 0, 0
| AgGlFgAppHistory.db | 264 | 1 | 72, 88, 96, 24, 32, 16, 16, 0, 0
| AgGlGlobalHistory.db | 264 | 1 | 72, 88, 96, 24, 32, 16, 16, 0, 0
| AgGlUAD_%SID%.db | [yellow-background]*264* | [yellow-background]*1* | [yellow-background]*72, 88, 96, 24, 32, 16, 16, 0, 0*
| | | |
| AgCx_SC#.db +
AgCx_SC#_xxxxxxxxxxxxxxxx.db | 236 | 11 | 72, 64, 88, 24, 24, 24, 24, 0, 0
| AgGlUAD_P_%SID%.db | 236 | 11 | 72, 64, 88, 24, 24, 24, 24, 0, 0
| AgCx_S#_%SID%.snp.db | 68 | 12 | 72, 64, 88, 24, 16, 16, 16, 0, 0
| | | |
| AgRobust.db | 156 | 14 | 72, 112, 144, 16, 16, 16, 16, 0, 0
|===

===== Database parameters

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The volume information entry size
| 4 | 4 | | The file information entry size
| 8 | 4 | | The source information entry size
| 12 | 4 | | [yellow-background]*The file information sub entry type 1 size*
| 16 | 4 | | [yellow-background]*The file information sub entry type 2 size*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | | [yellow-background]*Unknown*
| 28 | 4 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown*
|===

[yellow-background]*The source information sub entry type size ?*

=== Volume information entry

The size of the volume information entry is dependent on the corresponding
volume information entry size database parameter.

[NOTE]
The alignment in the volume information entry varies per architecture.

The volume information entry itself should start on an 8-byte aligned offset.

==== Volume information entry 56 (32-bit)

The volume information entry 56 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (identifier?)*
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Number of files (number of entries)
| 12 | 4 | 0x20000 | [yellow-background]*Unknown (flags?)*
| 16 | 8 | | [yellow-background]*Unknown*
| 24 | 8 | | Volume creation time +
Contains a FILETIME
| 32 | 4 | | Volume serial number
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 2 | | Volume device path number of characters +
The end-of-string character is not included.
| 46 | 2 | 0x0001 | [yellow-background]*Unknown* +
[yellow-background]*Flag for Unicode?*
| 48 | 8 | | [yellow-background]*Unknown*
| 56 | ... | | Volume device path +
an UTF-16 little-endian string with end-of-string character
| ... | ... | | Alignment padding +
4-byte alignment
| ... | ... | | Array of file information entries
|===

==== Volume information entry 72 (64-bit)

The volume information entry 72 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (identifier?)*
| 8 | 8 | | [yellow-background]*Unknown*
| 16 | 4 | | Number of files (number of entries)
| 20 | 4 | 0x20000 | [yellow-background]*Unknown (flags?)*
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 8 | | Volume creation time +
Contains a FILETIME
| 40 | 4 | | Volume serial number
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 8 | | [yellow-background]*Unknown*
| 56 | 2 | | Volume device path number of characters +
The end-of-string character is not included.
| 58 | 2 | 0x0001 | [yellow-background]*Unknown* +
[yellow-background]*Flag for Unicode?*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | ... | | Volume device path +
an UTF-16 little-endian string with end-of-string character
| ... | ... | | Alignment padding +
8-byte alignment
| ... | ... | | Array of file information entries
|===

=== File information entry

The size of the file information entry is dependent on the corresponding volume
information entry size database parameter.

[NOTE]
The alignment in the file information entry varies per architecture.

[yellow-background]*Note is this named section instead of file information entry?*

==== File information entry 36 (32-bit)

The file information entry 36 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | | Flags
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | 0x00080000 | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Internal section item hash?*
| 36 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
| 4-byte alignment
|===

==== File information entry 52 (32-bit)

The file information entry 52 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 16 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?* +
[yellow-background]*0 if not set*
| 20 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*2x 16-bit values?*
| 24 | 2 | | [yellow-background]*Unknown*
| 26 | 2 | 0x8000 | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 36 | 2 | | [yellow-background]*Unknown*
| 38 | 2 | | [yellow-background]*Unknown*
| 40 | 2 | | [yellow-background]*Unknown*
| 42 | 2 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
4-byte alignment
|===

....
Unknown values correspond with sub entry data, mostly only the first one

path number of characters                : 0x000001c9 (number of characters: 114, lower bits: 0x01)
unknown7                                 : 0x01828188
unknown8                                 : 0x00ba
unknown9                                 : 0x0009
unknown10                                : 0x0007
unknown11                                : 0x0e65
unknown12                                : 0x00000000
unknown13                                : 0x00050100

sub entry: 0 data:
00000000: e1 c0 c9 02 80 00 00 00  ba 00 09 00 07 00 65 0e   ........ ......e.

path number of characters                : 0x00000128 (number of characters: 74, lower bits: 0x00)
unknown7                                 : 0x01828188
unknown8                                 : 0x004e
unknown9                                 : 0x0006
unknown10                                : 0x0004
unknown11                                : 0x0019
unknown12                                : 0x00000000
unknown13                                : 0x00000000

sub entry: 0 data:
00000000: ac b0 cd 02 20 51 02 00  4e 00 4e 00 01 00 01 00   .... Q.. N.N.....

00000b90:                                      ac b0 cd 02   ..D.L.L. ........
00000ba0: 20 51 02 00 4e 00 4e 00  01 00 01 00 bc b0 cd 02    Q..N.N. ........

00000bb0: c0 b0 cd 02 20 21 02 00  4e 00 4e 00 01 00 01 00   .... !.. N.N.....
00000bc0: d0 b0 cd 02 d4 b0 cd 02  20 41 02 00 4e 00 4e 00   ........  A..N.N.
00000bd0: 01 00 01 00 e4 b0 cd 02  e8 b0 cd 02 20 61 02 00   ........ .... a..
....

==== File information entry 56 (32-bit)

....
struct PfRecordHeader_40
{
        DWORD64 unk01;
        DWORD nameHash;
        DWORD unk02;
        DWORD numOfSubEntries;
        DWORD unk03[7];
        DWORD nameLenExt;               //nameLen multiplied by 4, do shift before use
        DWORD unk04[3];
};
....

The file information entry 56 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | 0x00000008 | Flags +
See section: <<file_information_entry_flags,Flags>>
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 8 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 8 | | NTFS file reference +
See section: <<ntfs_file_reference,NTFS file reference>>
| 56 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
4-byte alignment
|===

==== File information entry 64 (64-bit)

The file information entry 64 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Number of entries
| 20 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 8 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown* +
[yellow-background]*Some identifier? Seems to be consistent for file information items in the same file.* +
 +
[yellow-background]*Linked to unknown2 of the next volume identifier?*
| 64 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== File information entry 72 (32-bit)

[yellow-background]*The file information entry 72 is used by the AgRobustdb
database and contains Least Recently Used file information?*

The file information entry 72 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | 0x00800000 | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*(internal identifier?)*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | 0x00000000 +
0x80000000 | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*(internal identifier?)*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 4 | | [yellow-background]*Unknown*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*(or NTFS file reference? Looks unlikely)*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
4-byte alignment
|===

==== File information entry 88 (64-bit)

The file information entry 88 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Number of entries
| 20 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown* +
[yellow-background]*Some identifier? Seems to be consistent for file information items in the same file.*
| 64 | 2 | | [yellow-background]*Unknown*
| 66 | 2 | | [yellow-background]*Unknown*
| 68 | 2 | | [yellow-background]*Unknown*
| 70 | 2 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | ...  | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ...  | ...  | | Alignment padding +
8-byte alignment
|===

==== File information entry 112 (64-bit)

[yellow-background]*TODO*
....
struct PfRecordHeader_70
{
        DWORD64 unk01;
        DWORD nameHash;
        DWORD unk02;
        DWORD numOfSubEntries;
        DWORD unk03[7];
        DWORD nameLenExt;               //nameLen multiplied by 4, do shift before use
        DWORD unk04[15];
};

00000030: 24 01 00 00 00 00 00 00  f0 82 d2 08 00 00 00 00   $....... ........
00000040: 01 00 00 c0 02 00 00 80  0f 39 5d 18 00 00 00 00   ........ .9].....
00000050: b0 83 ec 08 00 00 00 00  38 00 00 00 00 00 00 00   ........ 8.......
00000060: c2 a5 70 bf 20 03 00 00  f3 38 5d 18 01 00 00 00   ..p. ... .8].....
....

The file information entry 112 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Number of entries
| 20 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 8 | | [yellow-background]*Unknown*
| 40 | 8 | | [yellow-background]*Unknown*
| 48 | 4 | | Path number of characters +
The end-of-string character is not included. +
 +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | 8 | | [yellow-background]*Unknown*
| 96 | 8 | | [yellow-background]*Unknown*
| 104 | 8 | | [yellow-background]*Unknown*
| 112 | ...  | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== [[file_information_entry_flags]]Flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000008 | | [yellow-background]*Unknown; Has name?*
| | |
| 0x00000080 | | [yellow-background]*Is directory?*
| | |
| 0x00000200 | | [yellow-background]*Unknown*
|===

==== [[hash_function]]Hash function

The file information entry use the following hash function on in pseudo C.
....
*hash_value = 0x00004cb2fUL;

for( data_offset = 0;
     ( data_offset + 8 ) < data_size ;
     data_offset += 8)
{
    value_32bit  = data[ data_offset + 1 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 2 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 3 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 4 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 5 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 6 ];
    value_32bit *= 0x25;

    value_32bit += 0x1a617d0dUL * data[ data_offset ];

    *hash_value = value_32bit - ( 0x2fe8ed1fUL * *hash_value )
                + data[ data_offset + 7 ];
}

while( data_offset < data_size )
{
    *hash_value *= 0x25;
    *hash_value += data[ data_offset++ ];
}
....

The hash function is applied on the individual bytes of the UTF-16
little-endian string without the end-of-string character.

[yellow-background]*TODO; is there a separate 64-bit hash? On 64-bit platforms
the lower 32-bit of the name hash seems to be the same as in 32-bit databases.*

==== Sub entry type 1

===== Sub entry type 1 - 16

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | [yellow-background]*Unknown*
| 12 | 2 | | [yellow-background]*Unknown*
| 14 | 2 | | [yellow-background]*Unknown*
|===

===== Sub entry type 1 - 24 (64-bit)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 8 | 8 | | [yellow-background]*Unknown*
| 16 | 8 | | [yellow-background]*Unknown*
|===

==== Sub entry type 2

===== Sub entry type 2 - 16

[yellow-background]*TODO*

===== Sub entry type 2 - 20

[yellow-background]*TODO*

===== Sub entry type 2 - 24 (64-bit)

[yellow-background]*TODO*

===== Sub entry type 2 - 32

[yellow-background]*TODO*

=== Source information entry

The size of the source information entry is dependent on the corresponding
volume information entry size database parameter.

[yellow-background]*Type 60 and 88 used in database type 11 (AgCx_SC#.db, AgGlUAD_P_%SID%.db)*
[yellow-background]*Type 100 and 112 used in database type 11 (AgRobust.db)*

==== Source information entry 60 (32-bit)

The source information entry 60 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 8 | 4 | | Number of sub entries
| 12 | 4 | | [yellow-background]*Unknown (Flags?)* +
[yellow-background]*or 2x 16-bit values*
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 8 | | [yellow-background]*UnknownUnknown (empty values)* +
[yellow-background]*or 2x 32-bit values*
| 28 | 4 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 16 | | [yellow-background]*Unknown (empty values)*
|===

Seen in Vista database type 11 files (AgCx_SC#.db).

==== Source information entry 88 (64-bit)

The source information entry 88 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information +
[yellow-background]*(Or is the upper 32-bit an empty value?)*
| 16 | 4 | | Number of sub entries
| 20 | 4 | | [yellow-background]*Unknown (Flags?)* +
[yellow-background]*or 2x 16-bit values*
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 16 | | [yellow-background]*Unknown (empty values)* +
[yellow-background]*or 2x 64-bit values*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 16 | | [yellow-background]*Unknown (empty values)*
|===

Seen in Windows 7 database type 11 files (AgCx_SC#.db).

==== Source information entry 100 (32-bit)

....
00000000: 64 ba c2 04 89 e2 d4 48  00 00 00 00 08 00 00 00   d......H ........
00000010: 00 00 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000020: 00 00 00 00 89 e2 d4 48  00 00 00 00 54 41 53 4b   .......H ....TASK
00000030: 45 4e 47 2e 45 58 45 00  d0 f5 dd 01 b0 d5 c2 04   ENG.EXE. ........
00000040: b6 00 00 00 10 05 00 00  00 00 00 00 1f 6d 99 12   ........ .....m..
00000050: 00 00 00 00 01 00 00 00  08 00 00 00 d8 fd a6 04   ........ ........
00000060: 00 00 00 00                                        ....

00000000: 78 43 65 04 6c e7 4b 61  00 00 00 00 08 00 00 00   xCe.l.Ka ........
00000010: 00 00 00 00 00 00 00 00  00 00 00 00 02 00 00 00   ........ ........
00000020: 00 00 00 00 6c e7 4b 61  00 00 00 00 57 55 2d 57   ....l.Ka ....WU-W
00000030: 49 4e 44 4f 57 53 36 2e  31 2d 4b 00 88 a0 52 04   INDOWS6. 1-K...R.
00000040: 7f 00 00 00 66 02 00 00  40 02 00 00 00 00 00 00   ....f... @.......
00000050: 44 cb 05 18 00 00 00 00  00 00 00 00 00 00 00 00   D....... ........
00000060: 00 00 00 00
....

The source information entry 100 is used by the AgRobust.db database and
contains process information.

The source information entry 100 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 8 | 4 | | Number of sub entries
| 12 | 4 | 0x00000008 | [yellow-background]*Unknown (Flags?)*
| 16 | 12 | | [yellow-background]*Unknown (empty values)*
| 28 | 4 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | Prefetch hash
| 40 | 4 | | [yellow-background]*Unknown (empty values)*
| 44 | 16 | | Executable filename +
ASCII string with end-of-string character +
Unused bytes can contain remnant data +
[yellow-background]*Can also be an empty string?*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*(internal identifier?)*
| 84 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*(internal identifier?)*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown (some flag? end of list?)* +
[yellow-background]*0 or 1*
|===

Note that the executable filename will store a maximum of 15 characters.

==== Source information entry 144 (64-bit)

....
00000000: c9 af f0 08 00 00 00 00  fe 3f 04 00 00 00 00 00   ........ .?......
00000010: 00 00 00 00 08 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........

00000030: 02 00 00 00 00 00 00 00  fe 3f 04 00 00 00 00 00   ........ .?......
00000040: 00 00 00 00 00 00 00 00  53 45 54 55 50 2e 45 58   ........ SETUP.EX
00000050: 45 00 00 00 30 3c fa 04  88 3d 63 0d 00 00 00 00   E...0<.. .=c.....
00000060: 57 00 00 00 00 00 00 00                            W....... ........

00000060:                          00 00 00 00 00 00 00 00   W....... ........
00000070: 00 00 00 00 17 57 60 18  00 00 00 00 00 00 00 00   .....W`. ........
00000080: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
....

The source information entry 144 is used by the AgRobustdb database and
contains process information.

The source information entry 144 is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information +
[yellow-background]*(Or is the upper 32-bit an empty value?)*
| 16 | 4 | | Number of sub entries
| 20 | 4 | 0x00000008 | [yellow-background]*Unknown (Flags?)*
| 24 | 24 | | [yellow-background]*Unknown (empty values)*
| 48 | 4 | 2 | [yellow-background]*Unknown* +
[yellow-background]*The # in HARDDISKVOLUME#?*
| 52 | 4 | | [yellow-background]*Unknown (empty values)*
| 56 | 8 | | Prefetch hash
| 64 | 8 | | [yellow-background]*Unknown (empty values)*
| 72 | 16 | | Executable filename +
ASCII string with end-of-string character +
Unused bytes can contain remnant data +
[yellow-background]*Can also be an empty string?*
| 88 | 8 | | [yellow-background]*Unknown*
| 96 | 8 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown (empty values)*
| 116 | 4 | | [yellow-background]*Unknown*
| 120 | 4 | | [yellow-background]*Unknown (empty values)*
| 124 | 4 | | [yellow-background]*Unknown (empty values)*
| 128 | 8 | | [yellow-background]*Unknown (empty values)*
| 136 | 8 | | [yellow-background]*Unknown (empty values)*
|===

==== Sub entry type X

Seen in combination with source information entry 60 and 88

Uncertain which of the sub entry values is this.

Are these the traces?

===== Sub entry type X - 16 (32-bit)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | [yellow-background]*Unknown*
|===
| Offset | Size | Value | Description

===== Sub entry type X - 24 (64-bit)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | [yellow-background]*Unknown*
| 16 | 8 | | [yellow-background]*Unknown*
|===

== Notes

[yellow-background]*`[MSDN]` claims SuperFetch encrypts using 128-bit Advanced
Encryption Standard (AES) to ensure security of the data. Or is this only part
of ReadyBoost?*

What is the meaning of the acronyms:

* AgAl
* AgCx
* AgGl
* AgGlUAD
* AgPd
* AgRp (Related to AgRobust)
* AgTw

Range list data type?
Event info data type?
Scenario id data type?

PfFg file
PfHi file
PfSc file
PfSp file
PfTrx file
PfUD file

AgRB => ReadyBoot or ReadyBoost ?

=== Hash?

SiEntry?
x = 0x00b15dcb
x += byte
x *= 0x25
x += byte
x *= 0x25
x += byte
x *= 0x25
x += byte

=== AgAppLaunch.db

....
Number of entries

00000000  05 00 00 00 58 19 05 00  06 00 00 00 00 00 00 00  |....X...........|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000130  51 4a 50 01 00 00 00 00  54 76 e9 d5 00 00 00 00  |QJP.....Tv......|
00000140  80 65 4f 01 00 00 00 00  60 4a 50 01 00 00 00 00  |.eO.....`JP.....|
00000150  01 03 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

Entry:
00000160  51 4a 50 01 00 00 00 00  fb 56 64 0c 00 00 00 00  |QJP......Vd.....|
00000170  40 65 4f 01 00 00 00 00  c0 0b 77 04 00 00 00 00  |@eO.......w.....|
00000180  01 02 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

00000190  51 4a 50 01 00 00 00 00  81 09 d3 0b 00 00 00 00  |QJP.............|
000001a0  90 48 54 01 00 00 00 00  80 65 4f 01 00 00 00 00  |.HT......eO.....|
000001b0  01 02 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

000001c0  51 4a 50 01 00 00 00 00  9b 39 ad 9c 00 00 00 00  |QJP......9......|
000001d0  40 8d 56 01 00 00 00 00  40 65 4f 01 00 00 00 00  |@.V.....@eO.....|
000001e0  01 05 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

000001f0  51 4a 50 01 00 00 00 00  1a 65 9c c0 00 00 00 00  |QJP......e......|
00000200  a0 9a 6a 04 00 00 00 00  90 48 54 01 00 00 00 00  |..j......HT.....|
00000210  01 05 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

00000220  51 4a 50 01 00 00 00 00  62 60 17 ba 00 00 00 00  |QJP.....b`......|
00000230  60 4a 50 01 00 00 00 00  40 8d 56 01 00 00 00 00  |`JP.....@.V.....|
00000240  01 05 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

00000250  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00051950  00 00 00 00 00 00 00 00                           |........|
00051958
....

=== Unexplained

[yellow-background]*AgGlFaultHistory.db (Vista) with changing file information
sub entry type size. What in the format marks to use the sub entry type 2 ?*

[yellow-background]*AgGlFaultHistory.db (Windows 7)*

=== Database type and parameters

BtDb type
CrDb type X, 0x54, 0x24, ....
NvcDb type
PfDb type

19 (0x13) supported database types on Windows 7?
....
;PfFileParams PfDbDatabaseParamsForFileType[]

00: PfFileParams < 38h,  24h,  3Ch,    8,    8,    8,    8, 0, 0>
01: PfFileParams < 38h,  34h,  44h,  10h,  14h,    8,    8, 0, 0>
02: PfFileParams < 38h,  2Ch,  44h,  10h,    8,    8,    8, 0, 0>
03: PfFileParams < 38h,  24h,  3Ch,    8,    8,  14h,    8, 0, 0>
XX: PfFileParams 6 dup(<0, 0, 0, 0, 0, 0, 0, 0, 0>)
0A: PfFileParams < 38h,  24h,  3Ch,    8,    8,  0Ch,    8, 0, 0>
0B: PfFileParams < 38h,  24h,  3Ch,  10h,  10h,  10h,  10h, 0, 0>
0C: PfFileParams < 38h,  24h,  3Ch,  0Ch,    8,    8,    8, 0, 0>
0D: PfFileParams <0, 0, 0, 0, 0, 0, 0, 0, 0>
0E: PfFileParams < 38h,  48h,  64h,    8,    8,    8,    8, 0, 0>
0F: PfFileParams < 40h,  28h,  3Ch,    8,    8,  14h,    8, 0, 0>
10: PfFileParams < 38h,  2Ch,  68h,  10h,  18h,  14h,  1Ch, 0, 0>
11: PfFileParams <0, 0, 0, 0, 0, 0, 0, 0, 0>
12: PfFileParams < 48h,  2Ch,  3Ch,    8,    8,    8,    8, 0, 0>
....

=== TRX

Does the trx file contain the nvc trace data? Or PfTrx File?

=== Trace#.fx

[yellow-background]*Prefetcher trace file*

=== Notes

AgCx_S#_%SID%.snp.db
database parameters: 72, 64, 88, 24, 16, 16, 16, 0, 0
....
00000000: 58 b0 63 24 00 00 00 00  33 12 8b 26 d2 54 e5 f6   X.c$.... 3..&.T..
00000010: 82 0c 00 00 08 00 02 00  d0 f9 e6 25 00 00 00 00   ........ ...%....
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000030: 01 00 00 00 03 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000040: 00 00 00 00 00 00 00 00  53 65 73 73 69 6f 6e 00   ........ Session.
00000050: 00 00 00 00 00 00 00 00                            ........

unknown1                                   : 0x2463b058
unknown2                                   : 0xf6e554d2268b1233
number of entries                          : 3202
unknown4                                   : 0x00020008
unknown5                                   : 0x25e6f9d0
unknown6:
00000000: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........

unknown7                                   : 0x00000001
unknown8                                   : 0x00000003
unknown9                                   : 0x00000000
unknown10                                  : 0x00000000
unknown11:
....

Sub entry alignment issue; looks to be 24 instead of 16

....
00000000: 05 00 00 00 00 00 00 00  61 9f 63 24 00 00 00 00   ........ a.c$....
00000010: 00 4e 22 18 20 ff ff 1f  05 00 00 00 00 00 00 00   .N". ... ........
00000020: 61 9f 63 24 00 00 00 00  00 42 5b 18 20 ff ff 1f   a.c$.... .B[. ...
00000030: 05 00 00 00 00 00 00 00  61 9f 63 24 00 00 00 00   ........ a.c$....
00000040: 00 9c 53 18 20 ff ff 1f  05 00 00 00 00 00 00 00   ..S. ... ........
00000050: 61 9f 63 24 00 00 00 00                            a.c$....

unknown1                                   : 0x00000005
unknown2                                   : 0x24639f61
number of entries                          : 404901376
unknown4                                   : 0x1fffff20
unknown5                                   : 0x00000005
unknown6:
00000000: 61 9f 63 24 00 00 00 00  00 42 5b 18 20 ff ff 1f   a.c$.... .B[. ...

unknown7                                   : 0x00000005
unknown8                                   : 0x00000000
unknown9                                   : 0x24639f61
unknown10                                  : 0x1fffff2018539c00
unknown11:
00000000: 05 00 00 00 00 00 00 00  61 9f 63 24 00 00 00 00   ........ a.c$....
....

metrics relating to memory manager's standby-list?

Inside the profiles is information on how often pages are accessed and when
during the day.  Also, when background tasks force prefetched data out of
memory, SuperFetch writes scenario .db files so when the scenario occurs,
SuperFetch can fetch all or most of the recently evicted code and data and
place it back into memory.

SuperFetch also includes specific scenario support for hibernation, standby,
Fast User Switching (FUS), and application launch.

LRU lists in databases?

Robust:
* Section: LRU List entry?
* Source: Processes

Is there a AgCx_SC3.db Only seen SC1, SC2 and SC4 for now
sub entry type selection?

:numbered!:
[appendix]
== References

`[FORENSICWIKI]`

[cols="1,5",options="header"]
|===
| Title: | SuperFetch
| URL: | http://www.forensicswiki.org/wiki/SuperFetch
|===

`[LIBSCCA]`

[cols="1,5",options="header"]
|===
| Title: | Windows Prefetch File (PF) format
| Date: | November 2011
| Author(s): | Joachim Metz
| URL: | https://googledrive.com/host/0B3fBvzttpiiSbl9XZGZzQ05hZkU/Windows%20Prefetch%20File%20(PF)%20format.pdf
|===

`[REWOLF11]`

[cols="1,5",options="header"]
|===
| Title: | Windows SuperFetch file format - partial specification
| URL: | http://blog.rewolf.pl/blog/?p=214#.U0waAnWSwyO
|===

`[RUSSINOVICH07]`

[cols="1,5",options="header"]
|===
| Title: | Inside the Windows Vista Kernel: Part 2
| Date | 	March 2007
| Author(s): | Mark Russinovich
| URL: | http://technet.microsoft.com/en-us/magazine/2007.03.vistakernel.aspx
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | Windows PC Accelerators
| Date: | September 30, 2010
| Author(s): | Microsoft
| URL: | http://download.microsoft.com/download/3/0/2/3027D574-C433-412A-A8B6-5E0A75D5B237/perfaccel.docx
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

