= Windows SuperFetch database format

Analysis of AGDB

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

A Windows SuperFetch database file is used by Microsoft Windows as part of a
memory management to analyze memory usage patterns over time to optimize memory
content. This specification is based on earlier work on the format and was
enhanced by analyzing test data.

This document is intended as a working document of the data format specification
for the libagdb project.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Windows SuperFetch database format
| Classification: | Public
| Keywords: | SuperFetch
|===

[preface]
== License

....
Copyright (C) 2014-2026, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | April 2014 | Initial version.
| 0.0.2 | J.B. Metz | May 2014 | Additional findings.
| 0.0.3 | J.B. Metz | June 2014 | Additional findings.
| 0.0.4 | J.B. Metz | December 2014 | Switched to asccidoc format.
| 0.0.5 | J.B. Metz | November 2016 | Moved compression information to libfwnt documentation.
| 0.0.6 | J.B. Metz | December 2019 | Changes to formatting.
| 0.0.7 | J.B. Metz | February 2021 | Textual changes.
| 0.0.8 | J.B. Metz | June 2026 | Additional findings.
|===

:numbered:
== Overview

A Windows SuperFetch database file is used by Microsoft Windows as part of a
memory management to analyze memory usage patterns over time to optimize memory
content.

From `[MSDN]` SuperFetch prioritizes the following kinds of pages to remain in
memory:

* Pages of applications that are used most frequently overall.
* Pages of applications that are commonly used when resuming:
** After extensive hibernation (for example, first thing in the morning).
** After shorter periods of sleep or hibernation (for example, after lunch).

SuperFetch is implemented in %SystemRoot%\System32\sysmain.dll as a Windows
service that runs inside a Service Host process
(%SystemRoot%\System32\svchost.exe).

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | FILETIME in UTC
| Character strings | ASCII strings are Single Byte Character (SBC) or Multi Byte Character (MBC) string stored with a codepage. Sometimes referred to as ANSI string representation. +
Though technically maybe incorrect, this document will use term (extended) ASCII string. +
Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

=== Test version

Files created by the following version of programs were used to test the
information within this document:

* Windows Vista (SP0)
* Windows 7 (SP0)
* Windows 8.0
* Windows 8.1
* Windows 10 (1511)
* Windows 11 (25H2)

=== SuperFetch files

The SuperFetch files can be found in:

....
C:\Windows\Prefetch\
....

The SuperFetch database filenames are structured as:

....
Ag*.db
....

Various known database filenames are:

[cols="1,5",options="header"]
|===
| Filename | Description
| AgAppLaunch.db | [yellow-background]*Unknown; Different format?*
| AgCx_SC#.db +
AgCx_SC#_xxxxxxxxxxxxxxxx.db | [yellow-background]*Unknown; scenario databases?* +
Can contain executable information +
Where # is a decimal digit and x a hexadecimal digit. +
 +
Seen: +
AgCx_SC1.db, AgCx_SC2.db, AgCx_SC4.db +
AgCx_SC3_xxxxxxxxxxxxxxxx.db +
| AgCx_SC#_%SID%.snp.db | [yellow-background]*Unknown* +
Where # is a decimal digit and %SID% is a Windows NT Security identifier.
| AgGlFaultHistory.db | [yellow-background]*Unknown; History of Page Faults?*
| AgGlFgAppHistory.db | [yellow-background]*Unknown; History of foreground applications?*
| AgGlGlobalHistory.db | [yellow-background]*Unknown*
| AgGlUAD_%SID%.db | [yellow-background]*Unknown; User Assist related?* +
Where %SID% is a Windows NT Security identifier.
| AgGlUAD_P_%SID%.db | [yellow-background]*Unknown; User Assist related?* +
Where %SID% is a Windows NT Security identifier. +
Can contain executable information
| AgRobust.db | Robust performance database +
Robust performance (or robustness) is a component of SuperFetch to watch for specific file I/O access that might harm system performance by populating the standby lists with unneeded data. +
 +
The source information contains process information including prefetch hashes.
| AgTwCont.db | [yellow-background]*Unknown; not seen*
| HIDBG-*-*-*.db | [yellow-background]*Unknown; not seen*
| LongTermHist.db | [yellow-background]*Unknown; not seen*
| NvGeneralUseCore.db | [yellow-background]*Unknown; not seen* +
[yellow-background]*Related to %SystemRoot%\System32\Nv ?*
| NvGeneralUseCore_Round*.db | [yellow-background]*Unknown; not seen* +
[yellow-background]*Related to %SystemRoot%\System32\Nv ?*
| NoPfnRefPages*.db | [yellow-background]*Unknown; not seen*
| NvcBoot.db | [yellow-background]*Unknown; not seen*
| NvcHiber.db | [yellow-background]*Unknown; not seen*
| Prefetch_%HASH%_*.db | [yellow-background]*Unknown; not seen* +
Where %HASH% is [yellow-background]*TODO*
| PfnDBCore*.db | [yellow-background]*Unknown; not seen*
| PfnDBKnown*.db | [yellow-background]*Unknown; not seen*
| PfnDBNoPFNEntry*.db | [yellow-background]*Unknown; not seen*
| PfnDBNoUDEntry*.db | [yellow-background]*Unknown; not seen*
| StorePages*.db | [yellow-background]*Unknown; not seen*
| WsCompPages*.db | [yellow-background]*Unknown; not seen*
| .core.db | [yellow-background]*Unknown; not seen*
| *.h.db | [yellow-background]*Unknown; not seen*
|===

The SuperFetch service is managed by the File Information FS MiniFilter
service. It appears that most of the SuperFetch database files are updated
(written) when the service is shut down. AgAppLaunch.db is also written when
the service starts.

These database files can be stored in multiple formats:

[cols="1,1",options="header"]
|===
| Characteristics | Description
| Compressed SuperFetch database - MAM file format | Used in Windows 8.1, 10 and 11
| Compressed SuperFetch database - MEMO file format | Used in Windows Vista
| Compressed SuperFetch database - MEM0 file format | Used in Windows 7
| Compressed SuperFetch database - MEM\xb0 file format | Used in Windows 8.0
| Uncompressed SuperFetch database file format | Used in Windows Vista, 7 and 8
|===

The SuperFetch database [yellow-background]*trace* filenames are structured as:

....
Ag*.db.trx
....

== Compressed SuperFetch database - MEMO file format

A compressed SuperFetch database - MEMO file consist of the following
distinguishable elements:

* file header
* compressed blocks

The compression method is LZNT1

=== File header

The file header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MEMO" (0x4d, 0x45, 0x4d, 0x4f) | Signature
| 4 | 4 | | Total uncompressed data size
|===

=== Compressed block

The compressed block size is the chunk data size, which is part of the LZNT1
compressed data, + 2 bytes for the size of the chunk header itself.

The uncompressed block size is 4096 (0x1000) or the remaining uncompressed data
size for the last block.

For more information about LZNT1 see:
https://github.com/libyal/libfwnt/blob/main/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Compressed SuperFetch database - MEM0 file format

A compressed SuperFetch database - MEM0 file consist of the following
distinguishable elements:

* file header
* compressed blocks

The compression method is Microsoft XPRESS Huffman (or LZXPRESS). Note that
this is a different compression method as Microsoft XPRESS (LZ77+DIRECT2).

=== File header

The file header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MEM0" (0x4d, 0x45, 0x4d, 0x30) | Signature
| 4 | 4 | | Total uncompressed data size
|===

=== Compressed block

The compressed block is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Compressed data size
| 4 | ... | | LZXPRESS Huffman compressed data
|===

The uncompressed block size is 65536 (0x10000) or the remaining uncompressed
data size for the last block.

For more information about LZXPRESS Huffman see:
https://github.com/libyal/libfwnt/blob/main/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Compressed SuperFetch database - MEM\xb0 file format

A compressed SuperFetch database - MEM\xb0 file consist of the following
distinguishable elements:

* file header
* compressed blocks

The compression method is Microsoft XPRESS Huffman (or LZXPRESS). Note that
this is a different compression method as Microsoft XPRESS (LZ77+DIRECT2).

=== File header

The file header is 12 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MEM\xb0" (0x4d, 0x45, 0x4d, 0xb0) | Signature
| 4 | 4 | | Total uncompressed data size
| 8 | 4 | | [yellow-background]*Unknown (checksum?)*
|===

=== Compressed block

The compressed block is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Compressed data size
| 4 | ... | | LZXPRESS Huffman compressed data
|===

The uncompressed block size is:

* 65536 (0x10000) for Windows 8.0 and 8.1;
* 131072 (0x20000) for Windows 10;
* 1441792 (0x160000) for Windows 11;
* or the remaining uncompressed data size for the last block.

For more information about LZXPRESS Huffman see:
https://github.com/libyal/libfwnt/blob/main/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Compressed SuperFetch database - MAM file format

A compressed SuperFetch database - MAM file consist of the following
distinguishable elements:

* file header
* compressed stream

The compression method is Microsoft XPRESS Huffman (or LZXPRESS). Note that
this is a different compression method as Microsoft XPRESS (LZ77+DIRECT2).

=== File header

The file header is 12 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MAM\x84" (0x4d, 0x41, 0x4d, 0x84) | Signature
| 4 | 4 | | Total uncompressed data size
| 8 | 4 | | [yellow-background]*Unknown (checksum?)*
|===

=== Compressed stream

The compressed stream is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | LZXPRESS Huffman compressed data
|===

The compression stream differs from the compressed blocks as used in the MEM0
and MEM\xb0 formats. In the stream the compressed data can refer to uncompressed
data stored in previous compressed chunks.

For more information about LZXPRESS Huffman see:
https://github.com/libyal/libfwnt/blob/main/documentation/Compression%20methods.asciidoc[LIBFWNT\]].

== Uncompressed SuperFetch database file format

An uncompressed SuperFetch database consist of the following distinguishable elements:

* file header
** database header
* volume information entries
** file information entries
* source information entries

=== Common data structures

==== [[ntfs_file_reference]]NTFS file reference

The NTFS file reference is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 6 | | MFT entry index
| 6 | 2 | | Sequence number
|===

=== File header

The file header is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Signature (or database type)
| 4 | 4 | | Total file size
| 8 | 4 | | File header size
| 12 | ... | | Database header
| ... | ... | | Alignment padding +
8-byte alignment
|===

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000003 | | Windows 8.0, 8.1, 10 or 11 compressed database
| | |
| 0x00000005 | | Uncompressed AgAppLaunch.db database
| | |
| 0x0000000e | | Windows Vista or Windows 7 database uncompressed AgRobust.db or compressed database
| 0x0000000f | | Windows 8.0, 8.1, 10 or 11 uncompressed AgRobust.db database
|===

==== Database header

===== Common database header

The common database header is 60 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Database type +
See section: <<database_types_and_parameters,Database types and parameters>>
| 12 | 4 x 9 = 36 | | Database parameters
| 40 | 4 | | Number of volumes
| 44 | 4 | | Total number of files
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | 4 | | Number of sources
| 56 | 4 | | [yellow-background]*Unknown*
|===

===== Database header 68 (64-bit)

The database header 68 (64-bit) is 68 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
|===

===== Database header 116 (32-bit)

The database header 116 (32-bit) is 116 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | 5 | [yellow-background]*Unknown* +
[yellow-background]*(hard coded to be 5?)*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown (Empty values?)*
|===

===== Database header 156 (64-bit)

The database header 156 (64-bit) is 156 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | 5 | [yellow-background]*Unknown (number of following 8 byte values including itself?)*
| 64 | 4 | 0 | [yellow-background]*Unknown*
| 68 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 76 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 84 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 92 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown (number of following 8 byte values?)*
| 108 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 116 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 124 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 132 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 140 | 4 | | [yellow-background]*Unknown*
| 144 | 4 | | [yellow-background]*Unknown*
| 148 | 8 | | [yellow-background]*Unknown*
|===

===== Database header 228 (32-bit)

The database header 228 (32-bit) is 228 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | Number of date and time values
| 108 | 15 x 8 = 120 | | Date and time values +
Array of FILETIME values +
Unused entries are set to 0
|===

===== Database header 232 (32-bit)

TODO: complete section

===== Database header 236 (64-bit)

The database header 236 (64-bit) is 236 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown (empty values)* +
[yellow-background]*Number of date and time values?*
| 116 | 15 x 8 = 120 | | Date and time values +
Array of FILETIME values +
Unused entries are set to 0
|===

===== Database header 264 (32 and 64-bit)

The database header 264 is 264 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown (empty values)*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown*
| 116 | 4 | | [yellow-background]*Unknown*
| 120 | 4 | | [yellow-background]*Unknown*
| 124 | 4 | | [yellow-background]*Unknown*
| 128 | ... | | [yellow-background]*TODO*
| 224 | 8 | | [yellow-background]*Unknown (empty values)*
| 232 | 32 | | Database filename +
ASCII string with end-of-string character +
Unused bytes are set to 0
|===

===== Database header 272 (32 and 64-bit)

The database header 272 is 272 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 | | Common database header
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown (empty values)*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown*
| 116 | 4 | | [yellow-background]*Unknown*
| 120 | 4 | | [yellow-background]*Unknown*
| 124 | 4 | | [yellow-background]*Unknown*
| 128 | ... | | [yellow-background]*TODO*
| 224 | 16 | | [yellow-background]*Unknown (empty values)*
| 240 | 32 | | Database filename +
ASCII string with end-of-string character +
Unused bytes are set to 0
|===

==== [[database_types_and_parameters]]Database types and parameters

`[REWOLF11]` states that the database type is an index of a table that is
located in sysmain.dll and that the 9 32-bit values that follow the database
type are parameters (named database parameters in this document).

These database parameters seem to specify the sizes of the structures used in
the sections that follow the file header. The values of the database parameters
seem to be dependent on the architecture of sysmain.dll.

===== Windows Vista and Windows 7 databases

[cols="3,1,1,3",options="header"]
|===
| Filename | Number of bits | Database header size | Database type | Database parameters
| AgGlFaultHistory.db | 32-bit | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlFaultHistory.db | 64-bit | 264 | 1 | 72, 88, 96, 24, 32, 16, 16, 0, 0
| AgGlFgAppHistory.db | 32-bit | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlFgAppHistory.db | 64-bit | 264 | 1 | 72, 88, 96, 24, 32, 16, 16, 0, 0
| AgGlGlobalHistory.db | 32-bit | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlGlobalHistory.db | 64-bit | 264 | 1 | 72, 88, 96, 24, 32, 16, 16, 0, 0
| AgGlUAD_%SID%.db | 32-bit | 264 | 1 | 56, 52, 68, 16, 20, 8, 8, 0, 0
| AgGlUAD_%SID%.db | 64-bit | | |
| | | | |
| AgCx_SC#.db | 32-bit | 228 | 11 | 56, 36, 60, 16, 16, 16, 16, 0, 0
| AgCx_SC#.db | 64-bit | 236 | 11 | 72, 64, 88, 24, 24, 24, 24, 0, 0
| AgCx_SC#_xxxxxxxxxxxxxxxx.db | 32-bit | 228 | 11 | 56, 36, 60, 16, 16, 16, 16, 0, 0
| AgCx_SC#_xxxxxxxxxxxxxxxx.db | 64-bit | 236 | 11 | 72, 64, 88, 24, 24, 24, 24, 0, 0
| AgGlUAD_P_%SID%.db | 32-bit | 232 | 11 | 56, 36, 60, 16, 16, 16, 16, 0, 0
| AgGlUAD_P_%SID%.db | 64-bit | 236 | 11 | 72, 64, 88, 24, 24, 24, 24, 0, 0
| AgCx_S#_%SID%.snp.db | | | |
| | | | |
| AgRobust.db | 32-bit | 116 | 14 | 56, 72, 100, 8, 8, 8, 8, 0, 0
| AgRobust.db | 64-bit | 156 | 14 | 72, 112, 144, 16, 16, 16, 16, 0, 0
|===

===== Windows 8.0, 8.1, 10 and 11 databases

[cols="3,1,1,3",options="header"]
|===
| Filename | Number of bits | Database header size | Database type | Database parameters
| AgGlFaultHistory.db | 32-bit | 272 | 21 | 72, 48, 60, 16, 20, 8, 8, 0, 0
| AgGlFaultHistory.db | 64-bit | 272 | 21 | 96, 80, 88, 16, 24, 8, 8, 0, 0
| AgGlFgAppHistory.db | 32-bit | 272 | 21 | 72, 48, 60, 16, 20, 8, 8, 0, 0
| AgGlFgAppHistory.db | 64-bit | 272 | 21 | 96, 80, 88, 16, 24, 8, 8, 0, 0
| AgGlGlobalHistory.db | 32-bit | 272 | 21 | 72, 48, 60, 16, 20, 8, 8, 0, 0
| AgGlGlobalHistory.db | 64-bit | 272 | 21 | 96, 80, 88, 16, 24, 8, 8, 0, 0
| AgGlUAD_%SID%.db | 32-bit | | |
| AgGlUAD_%SID%.db | 64-bit | 272 | 21 | 96, 80, 88, 16, 24, 8, 8, 0, 0
| | | | |
| AgCx_SC4.db | 32-bit | | |
| AgCx_SC4.db | 64-bit | 220 | 11 | 96, 56, 80, 16, 16, 16, 16, 0, 0
| AgGlUAD_P_%SID%.db | 32-bit | | |
| AgGlUAD_P_%SID%.db | 64-bit | 220 | 11 | 96, 56, 80, 16, 16, 16, 16, 0, 0
| | | | |
| AgRobust.db | 32-bit | 116 | 14 | 56, 72, 100, 8, 8, 8, 8, 0, 0
| AgRobust.db | 64-bit | 156 | 14 | 72, 112, 144, 16, 16, 16, 16, 0, 0
|===

===== Database parameters

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The volume information entry size
| 4 | 4 | | The file information entry size
| 8 | 4 | | The source information entry size
| 12 | 4 | | The file information sub entry type 1 size
| 16 | 4 | | The file information sub entry type 2 size
| 20 | 4 | | [yellow-background]*Unknown (The source information sub entry type 1 size)*
| 24 | 4 | | [yellow-background]*Unknown (The source information sub entry type 2 size)*
| 28 | 4 | 0 | [yellow-background]*Unknown*
| 32 | 4 | 0 | [yellow-background]*Unknown*
|===

[yellow-background]*The source information sub entry type size ?*

=== Volume information entry

The size of the volume information entry is dependent on the corresponding
volume information entry size database parameter.

[NOTE]
The alignment in the volume information entry varies per architecture.

The volume information entry itself should start on an 8-byte aligned offset.

==== Windows Vista and Windows 7 databases

===== Volume information entry 56 (32-bit)

The volume information entry 56 (32-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Number of files (file information entries)
| 12 | 4 | | [yellow-background]*Unknown (flags?)*
| 16 | 8 | | [yellow-background]*Unknown*
| 24 | 8 | | Volume creation time +
Contains a FILETIME
| 32 | 4 | | Volume serial number
| 36 | 4 | 0 | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown (or 2 16-bit values?)*
| 44 | 2 | | Volume device path number of characters +
The end-of-string character is not included.
| 46 | 2 | 0x0001 | [yellow-background]*Unknown* +
[yellow-background]*Flag for Unicode?*
| 48 | 8 | | [yellow-background]*Unknown*
| 56 | ... | | Volume device path +
an UTF-16 little-endian string with end-of-string character
| ... | ... | | Alignment padding +
4-byte alignment
| ... | ... | | Array of file information entries
|===

==== Volume information entry 72 (64-bit)

The volume information entry 72 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | [yellow-background]*Unknown*
| 16 | 4 | | Number of files (file information entries)
| 20 | 4 | | [yellow-background]*Unknown (flags?)*
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 8 | | Volume creation time +
Contains a FILETIME
| 40 | 4 | | Volume serial number
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 8 | | [yellow-background]*Unknown*
| 56 | 2 | | Volume device path number of characters +
The end-of-string character is not included.
| 58 | 2 | 0x0001 | [yellow-background]*Unknown* +
[yellow-background]*Flag for Unicode?*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | ... | | Volume device path +
an UTF-16 little-endian string with end-of-string character
| ... | ... | | Alignment padding +
8-byte alignment
| ... | ... | | Array of file information entries
|===

===== Windows 8.0, 8.1, 10 and 11 databases

===== Volume information entry 72 (32-bit)

The volume information entry 72 (32-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Number of files (file information entries)
| 12 | 4 | | [yellow-background]*Unknown (flags?)*
| 16 | 8 | | [yellow-background]*Unknown*
| 24 | 8 | | Volume creation time +
Contains a FILETIME
| 32 | 4 | | Volume serial number
| 36 | 4 | 0 | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown (or 2 16-bit values?)*
| 44 | 2 | | Volume device path number of characters +
The end-of-string character is not included.
| 46 | 2 | 0x0001 | [yellow-background]*Unknown* +
[yellow-background]*Flag for Unicode?*
| 48 | 8 | | [yellow-background]*Unknown*
| 56 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 60 | 4 | | [yellow-background]*Unknown*
| 68 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 72 | ... | | Volume device path +
an UTF-16 little-endian string with end-of-string character
| ... | ... | | Alignment padding +
4-byte alignment
| ... | ... | | Array of file information entries
|===

===== Volume information entry 96 (64-bit)

The volume information entry 96 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 16 | 4 | | Number of files (number of entries)
| 20 | 4 | 0x20000 | [yellow-background]*Unknown (flags?)*
| 24 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 32 | 8 | | Volume creation time +
Contains a FILETIME
| 40 | 4 | | Volume serial number
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 56 | 2 | | Volume device path number of characters +
The end-of-string character is not included.
| 58 | 2 | 0x0001 | [yellow-background]*Unknown* +
[yellow-background]*Flag for Unicode?*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 96 | ... | | Volume device path +
an UTF-16 little-endian string with end-of-string character
| ... | ... | | Alignment padding +
8-byte alignment
| ... | ... | | Array of file information entries
|===

=== File information entry

The size of the file information entry is dependent on the corresponding volume
information entry size database parameter.

[NOTE]
The alignment in the file information entry varies per architecture.

[yellow-background]*Note is this named section instead of file information entry?*

==== Windows Vista and Windows 7 databases

===== File information entry 36 (32-bit)

The file information entry 36 is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | | Flags
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | 0x00080000 | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 36 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
| 4-byte alignment
|===

===== File information entry 52 (32-bit)

The file information entry 52 (32-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 16 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 20 | 2 | | [yellow-background]*Unknown*
| 22 | 2 | | [yellow-background]*Unknown*
| 24 | 2 | | [yellow-background]*Unknown*
| 26 | 2 | | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 36 | 2 | | [yellow-background]*Unknown*
| 38 | 2 | | [yellow-background]*Unknown*
| 40 | 2 | | [yellow-background]*Unknown*
| 42 | 2 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
4-byte alignment
|===

==== File information entry 64 (64-bit)

The file information entry 64 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Number of entries
| 20 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 24 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 32 | 8 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown* +
[yellow-background]*Some identifier? Seems to be consistent for file information items in the same file.* +
 +
[yellow-background]*Linked to unknown2 of the next volume identifier?*
| 64 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== File information entry 72 (32-bit)

The file information entry 72 (32-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Number of entries
| 12 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 16 | 4 | 0 | [yellow-background]*Unknown*
| 20 | 4 | 0 | [yellow-background]*Unknown*
| 24 | 4 | 0x00800000 | [yellow-background]*Unknown*
| 28 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 32 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 4 | | [yellow-background]*Unknown*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*(or NTFS file reference? Looks unlikely)*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
4-byte alignment
|===

==== File information entry 88 (64-bit)

The file information entry 88 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Number of entries
| 20 | 4 | | Flags +
See section: <<file_information_entry_flags,Flags>>
| 24 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 64 | 2 | | [yellow-background]*Unknown*
| 66 | 2 | | [yellow-background]*Unknown*
| 68 | 2 | | [yellow-background]*Unknown*
| 70 | 2 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown (file reference?)*
| 80 | 8 | | [yellow-background]*Unknown*
| 88 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== File information entry 112 (64-bit)

TODO: complete section

===== Windows 8.0, 8.1, 10 and 11 databases

==== File information entry 48 (32-bit)

The file information entry 48 (32-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | Name hash +
See section: <<hash_function,Hash function>>
| 8 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 12 | 4 | | [yellow-background]*Unknown*
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | | [yellow-background]*Unknown*
| 28 | 4 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
4-byte alignment
|===

==== File information entry 56 (64-bit)

The file information entry 56 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 32 | 4 | | Number of entries (TODO: determine value calculation)
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== File information entry 72 (32-bit)

TODO: complete section

==== File information entry 80 (64-bit)

The file information entry 80 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 32 | 8 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 2 | | [yellow-background]*Unknown*
| 58 | 2 | | [yellow-background]*Unknown*
| 60 | 2 | | [yellow-background]*Unknown*
| 62 | 2 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | Number of entries
| 80 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== File information entry 112 (64-bit)

The file information entry 112 (64-bit) is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
See section: <<hash_function,Hash function>>
| 16 | 4 | | Path number of characters, which does not include the end-of-string character. +
Note that the value must be divided by 4 first. The purpose of the lower 2 bits is unknown.
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown (flags?)*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown*
| 48 | 8 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown*
| 64 | 2 | | [yellow-background]*Unknown*
| 66 | 2 | | [yellow-background]*Unknown*
| 68 | 2 | | [yellow-background]*Unknown*
| 70 | 2 | | [yellow-background]*Unknown*
| 72 | 8 | | [yellow-background]*Unknown*
| 80 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 8 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | ... | | Path +
an UTF-16 little-endian string with end-of-string character +
 +
The path is relative from the root of the file system on the volume
| ... | ... | | Alignment padding +
8-byte alignment
|===

==== [[file_information_entry_flags]]Flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000008 | | [yellow-background]*Unknown; Has name?*
| | |
| 0x00000080 | | [yellow-background]*Is directory?*
| | |
| 0x00000200 | | [yellow-background]*Unknown*
| | |
| 0x00000800 | | [yellow-background]*Unknown*
|===

==== [[hash_function]]Hash function

The file information entry use the following hash function on in pseudo C.

....
*hash_value = 0x00004cb2fUL;

for( data_offset = 0;
     ( data_offset + 8 ) < data_size ;
     data_offset += 8)
{
    value_32bit  = data[ data_offset + 1 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 2 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 3 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 4 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 5 ];
    value_32bit *= 0x25;
    value_32bit += data[ data_offset + 6 ];
    value_32bit *= 0x25;

    value_32bit += 0x1a617d0dUL * data[ data_offset ];

    *hash_value = value_32bit - ( 0x2fe8ed1fUL * *hash_value )
                + data[ data_offset + 7 ];
}

while( data_offset < data_size )
{
    *hash_value *= 0x25;
    *hash_value += data[ data_offset++ ];
}
....

The hash function is applied on the individual bytes of the UTF-16 little-endian
string without the end-of-string character.

[yellow-background]*TODO; is there a separate 64-bit hash? On 64-bit platforms
the lower 32-bit of the name hash seems to be the same as in 32-bit databases.*

For Windows Vista and Windows 7 databases if sub entry flags 0x00000020 is set
then sub entry type 2 is used

==== Sub entry type 1

===== Sub entry type 1 - 16

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 4 | 4 | | [yellow-background]*Unknown (sub entry flags)*
| 8 | 2 | | [yellow-background]*Unknown*
| 10 | 2 | | [yellow-background]*Unknown*
| 12 | 2 | | [yellow-background]*Unknown*
| 14 | 2 | | [yellow-background]*Unknown*
|===

===== Sub entry type 1 - 24 (64-bit)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 8 | 8 | | [yellow-background]*Unknown*
| 16 | 8 | | [yellow-background]*Unknown*
|===

==== Sub entry type 2

===== Sub entry type 2 - 16

TODO: complete section

===== Sub entry type 2 - 20

Similar to Sub entry type 1 - 16 but with 4 bytes extra

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Some kind of identifier?*
| 4 | 4 | | [yellow-background]*Unknown (sub entry flags)*
| 8 | 2 | | [yellow-background]*Unknown*
| 10 | 2 | | [yellow-background]*Unknown*
| 12 | 2 | | [yellow-background]*Unknown*
| 14 | 2 | | [yellow-background]*Unknown*
| 16 | 4 | | [yellow-background]*Unknown*
|===

===== Sub entry type 2 - 24 (64-bit)

TODO: complete section

===== Sub entry type 2 - 32

TODO: complete section

=== Source information entry

The size of the source information entry is dependent on the corresponding
volume information entry size database parameter.

===== Windows Vista and Windows 7 databases

==== Source information entry 60 (32-bit)

The source information entry 60 (32-bit) is 60 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 8 | 4 | | Number of entries
| 12 | 4 | | [yellow-background]*Unknown (Flags?)*
| 16 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 20 | 8 | 0 | [yellow-background]*Unknown (empty values)*
| 28 | 4 | | [yellow-background]*Unknown (seen: 0, 1 or 2)*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 16 | | [yellow-background]*Unknown (empty values)*
|===

==== Source information entry 68 (32-bit)

TODO: complete section

==== Source information entry 88 (64-bit)

The source information entry 88 (64-bit) is 88 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information +
[yellow-background]*(Or is the upper 32-bit an empty value?)*
| 16 | 4 | | Number of entries
| 20 | 4 | | [yellow-background]*Unknown (Flags?)*
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 16 | | [yellow-background]*Unknown (empty values)* +
[yellow-background]*or 2x 64-bit values*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 8 | | [yellow-background]*Unknown*
| 64 | 8 | | [yellow-background]*Unknown*
| 72 | 16 | | [yellow-background]*Unknown (empty values)*
|===

==== Source information entry 96 (64-bit)

TODO: complete section

==== Source information entry 100 (32-bit)

The source information entry 100 (32-bit) is 100 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 8 | 4 | | [yellow-background]*Unknown (Number of entries?)*
| 12 | 4 | | [yellow-background]*Unknown (Flags?)*
| 16 | 4 | 0 | [yellow-background]*Unknown (empty values)*
| 20 | 4 | 0 | [yellow-background]*Unknown (empty values)*
| 24 | 4 | 0 | [yellow-background]*Unknown (empty values)*
| 28 | 4 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | Prefetch hash
| 40 | 4 | 0 | [yellow-background]*Unknown (empty values)*
| 44 | 16 | | Executable filename +
ASCII string with end-of-string character +
Unused bytes can contain remnant data +
[yellow-background]*Can also be an empty string?*
| 60 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 96 | 4 | | [yellow-background]*Unknown*
|===

Note that the executable filename will store a maximum of 15 characters.

==== Source information entry 144 (64-bit)

The source information entry 144 (64-bit) is 144 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information +
[yellow-background]*(Or is the upper 32-bit an empty value?)*
| 16 | 4 | | [yellow-background]*Unknown (Number of entries?)*
| 20 | 4 | | [yellow-background]*Unknown (Flags?)*
| 24 | 8 | 0 | [yellow-background]*Unknown (empty values)*
| 32 | 8 | 0 | [yellow-background]*Unknown (empty values)*
| 40 | 8 | 0 | [yellow-background]*Unknown (empty values)*
| 48 | 4 | | [yellow-background]*Unknown (# in HARDDISKVOLUME#?)*
| 52 | 4 | 0 | [yellow-background]*Unknown (empty values)*
| 56 | 8 | | Prefetch hash
| 64 | 8 | 0 | [yellow-background]*Unknown (empty values)*
| 72 | 16 | | Executable filename +
ASCII string with end-of-string character +
Unused bytes can contain remnant data +
[yellow-background]*Can also be an empty string?*
| 88 | 8 | | [yellow-background]*Unknown*
| 96 | 8 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown (empty values)*
| 116 | 4 | | [yellow-background]*Unknown*
| 120 | 4 | | [yellow-background]*Unknown (empty values)*
| 124 | 4 | | [yellow-background]*Unknown (empty values)*
| 128 | 8 | | [yellow-background]*Unknown (empty values)*
| 136 | 8 | | [yellow-background]*Unknown (empty values)*
|===

==== Sub entry type X

Seen in combination with source information entry 60 and 88

Uncertain which of the sub entry values is this.

Are these the traces?

===== Sub entry type X - 16 (32-bit)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | [yellow-background]*Unknown*
|===

===== Sub entry type X - 24 (64-bit)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 8 | | [yellow-background]*Unknown*
| 16 | 8 | | [yellow-background]*Unknown*
|===

===== Windows 8.0, 8.1, 10 and 11 databases

==== Source information entry 80 (64-bit)

The source information entry 80 (64-bit) is 80 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 8 | | [yellow-background]*Unknown*
| 32 | 8 | | [yellow-background]*Unknown (last execution time? contains a FILETIME)*
| 40 | 16 | | [yellow-background]*Unknown*
| 56 | 4 | | Number of entries
| 60 | 4 | 0 | [yellow-background]*Unknown (flags?)*
| 64 | 8 | 0 | [yellow-background]*Unknown*
| 72 | 8 | 0 | [yellow-background]*Unknown*
|===

==== Source information entry 100 (32-bit)

The source information entry 100 (32-bit) is 100 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (sequence number?)*
| 4 | 4 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 8 | 4 | | [yellow-background]*Unknown*
| 12 | 4 | | [yellow-background]*Unknown*
| 16 | 4 | | Prefetch hash
| 20 | 4 | 0 | [yellow-background]*Unknown (empty values)*
| 24 | 16 | | Executable filename +
ASCII string with end-of-string character +
Unused bytes can contain remnant data +
[yellow-background]*Can also be an empty string?*
| 40 | 4 | | [yellow-background]*Unknown (number of entries?)*
| 44 | 4 | | [yellow-background]*Unknown (flags?)*
| 48 | 4 | | [yellow-background]*Unknown*
| 52 | 4 | | [yellow-background]*Unknown*
| 56 | 4 | | [yellow-background]*Unknown*
| 60 | 4 | | [yellow-background]*Unknown*
| 64 | 4 | | [yellow-background]*Unknown*
| 68 | 4 | | [yellow-background]*Unknown*
| 72 | 4 | | [yellow-background]*Unknown*
| 76 | 4 | | [yellow-background]*Unknown*
| 80 | 4 | | [yellow-background]*Unknown*
| 84 | 4 | | [yellow-background]*Unknown*
| 88 | 4 | | [yellow-background]*Unknown*
| 92 | 4 | | [yellow-background]*Unknown*
| 96 | 4 | | [yellow-background]*Unknown*
|===

Note that the executable filename will store a maximum of 15 characters.

==== Source information entry 144 (64-bit)

The source information entry 144 (64-bit) is 144 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 8 | 8 | | Name hash +
Contains a copy of the prefetch hash see `[LIBSCCA]` for information
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 8 | | Prefetch hash
| 32 | 8 | 0 | [yellow-background]*Unknown*
| 40 | 16 | | Executable filename +
ASCII string without end-of-string character +
Unused bytes can contain remnant data +
[yellow-background]*Can also be an empty string?*
| 56 | 4 | 0 | [yellow-background]*Unknown (number of entries?)*
| 60 | 4 | | [yellow-background]*Unknown (flags?)*
| 64 | 8 | 0 | [yellow-background]*Unknown*
| 72 | 8 | 0 | [yellow-background]*Unknown*
| 80 | 8 | 0 | [yellow-background]*Unknown*
| 88 | 8 | | [yellow-background]*Unknown (sequence number?)*
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 4 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown*
| 116 | 4 | | [yellow-background]*Unknown*
| 120 | 8 | 0 | [yellow-background]*Unknown*
| 128 | 8 | 0 | [yellow-background]*Unknown*
| 136 | 8 | 0 | [yellow-background]*Unknown*
|===

Note that the executable filename will store a maximum of 15 characters.

:numbered!:
[appendix]
== References

`[FORENSICWIKI]`

[cols="1,5",options="header"]
|===
| Title: | SuperFetch
| URL: | http://www.forensicswiki.org/wiki/SuperFetch
|===

`[LIBSCCA]`

[cols="1,5",options="header"]
|===
| Title: | Windows Prefetch File (PF) format
| Date: | November 2011
| Author(s): | Joachim Metz
| URL: | https://googledrive.com/host/0B3fBvzttpiiSbl9XZGZzQ05hZkU/Windows%20Prefetch%20File%20(PF)%20format.pdf
|===

`[REWOLF11]`

[cols="1,5",options="header"]
|===
| Title: | Windows SuperFetch file format - partial specification
| URL: | http://blog.rewolf.pl/blog/?p=214#.U0waAnWSwyO
|===

`[RUSSINOVICH07]`

[cols="1,5",options="header"]
|===
| Title: | Inside the Windows Vista Kernel: Part 2
| Date | 	March 2007
| Author(s): | Mark Russinovich
| URL: | http://technet.microsoft.com/en-us/magazine/2007.03.vistakernel.aspx
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | Windows PC Accelerators
| Date: | September 30, 2010
| Author(s): | Microsoft
| URL: | http://download.microsoft.com/download/3/0/2/3027D574-C433-412A-A8B6-5E0A75D5B237/perfaccel.docx
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

